Explicitly ensure the output path is a block device
Fixes obscure error:

    Error: checking for exclusive access to foo
    Caused by: rereading partition table
    Caused by: ENOTTY: Not a typewriter