cmdline: don't require -h to list subcommands
The top-level coreos-installer command prints a list of subcommands if
run without arguments, but subcommands with subcommands don't:

    $ target/debug/coreos-installer iso
    Error: parsing arguments

    Caused by:
        unrecognized 'iso' subcommand

Enable the automatic subcommand list for subcommands with subcommands.
Don't enable it globally because that would enable it for leaf commands,
which precludes zero-argument commands like list-stream.